#!/bin/zsh

mkdir /tmp/old
mkdir /tmp/new

foreach i (/System/Library/Frameworks/*.framework) do
    echo $i `basename $i .framework`
    /usr/local/bin/class-dump -s $i >& /tmp/old/`basename $i .framework`.txt
    /Local/Public/nygard/Products/class-dump $i >& /tmp/new/`basename $i .framework`.txt
done
