#!/bin/zsh

TESTDIR=/tmp/cdt
TESTDIR_OLD=$TESTDIR/old
TESTDIR_NEW=$TESTDIR/new

OLD_CD=~/Unix/bin/class-dump
NEW_CD=/Local/nygard/Products/Release/class-dump

mkdir $TESTDIR $TESTDIR_OLD $TESTDIR_NEW

foreach i (/System/Library/Frameworks/*.framework /System/Library/PrivateFrameworks/*.framework) do
    echo $i `basename $i .framework`
    $OLD_CD -s -t $i >& "$TESTDIR_OLD/`basename $i .framework`-framework.txt"
    $NEW_CD -s -t $i >& "$TESTDIR_NEW/`basename $i .framework`-framework.txt"
done

foreach i (/Applications/*.app /Applications/Utilities/*.app) do
    echo $i `basename $i .app`
    $OLD_CD -s -t $i >& "$TESTDIR_OLD/`basename $i .app`-app.txt"
    $NEW_CD -s -t $i >& "$TESTDIR_NEW/`basename $i .app`-app.txt"
done
